# Generated by Django 3.1.1 on 2021-12-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211206_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nam',
            new_name='name',
        ),
    ]
