# Generated by Django 3.1.1 on 2021-12-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211207_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
